config/routes.rb
Rails.application.routes.draw do
  
  resources :subscriptions
  resources :confirmations
  resources :praises
  resources :books
  resources :series
  devise_for :users
  get 'landing/index'
  resources :posts

  resources :pages
  get '/:slug' => "pages#show"
  
  root to: 'landing#index'
end

app/views/pages/_form.html.erb
<%= form_with(model: page) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-input rounded w-full block' %>
  </div>

  <div class="mt-8">
    <%= form.rich_text_area :content %>
  </div>

  <div class="mt-8">
    <%= form.submit "Submit", class: button_css('blue') %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<div class="max-w-2xl mx-auto">
<%= headline("Editing: #{@page.title}") %>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>
</div>

app/views/pages/index.html.erb
<div class="max-w-2xl mx-auto">
<%= headline('Pages') %>
<% @pages.each do |page| %>
  <article class="px-8 py-4 my-8 border rounded-lg shadow-lg">
    <%= h2(page.title, "text-center mt-2 mb-4") %>
    <p class='prose lg:prose-xl'><%= page.content.to_plain_text.truncate(256) %></p>
    <p class='my-4 text-center'>
    <%= link_to 'Read More', page, class: button_css('purple') %>
    <%= link_to 'Edit Page', edit_page_path(page), class: button_css('blue') %>
    <%= link_to 'Destroy Page', edit_page_path(page), class: button_css('red') %>
    </p>
    
  </article>
<% end %>
<%= link_to 'New Page', new_page_path, class: button_css('blue') %>
</div>

<br>

app/views/pages/new.html.erb
<div class="max-w-2xl mx-auto">
<%= headline('New Page') %>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>
</div>

app/views/pages/show.html.erb
<article class="<%=t('css_article')%>">
  <%= render 'components/actions', obj: @page %>
  <div class="text-center"><%= headline(@page.title) %></div>
  <section class="<%=t('css_prose')%>">
    <%= @page.content %>
  </section>
</article>