config/routes.rb
Rails.application.routes.draw do
  
  resources :subscriptions
  resources :confirmations
  resources :praises
  resources :books
  resources :series
  devise_for :users
  get 'landing/index'
  resources :posts

  resources :pages
  get '/:slug' => "pages#show"
  
  root to: 'landing#index'
end

app/models/post.rb
class Post < ApplicationRecord
  has_rich_text :content

  include Sluggable
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[show index]
  load_and_authorize_resource
  

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find_using_slug(params[:id])
      # @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :published_at)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-input rounded block w-full' %>
  </div>

  <div class="mt-8">
    <%= form.rich_text_area :content %>
  </div>

  <div class="field">
    <%= form.label :published_at %>
    <%= form.datetime_select :published_at %>
  </div>

  <div class="actions">
    <%= form.submit "Submit", class: button_css('blue') %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="max-w-2xl mx-auto">
<%= headline("Editing '#{@post.title}'") %>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %>
</div>

app/views/posts/index.html.erb
<div class="max-w-2xl mx-auto">
    <% headline("Posts") %>
    <% if user_signed_in? %>
      <div class="mt-8">
      <%= link_to 'New Post', new_post_path, class: button_css('red') %>
      </div>
    <% end %>
    
    <%= render 'components/subscribe' %>

    <% @posts.each do |post| %>
      <article class="px-8 py-4 my-8 border rounded-lg shadow-lg">
        <aside class="text-center text-gray-500 opacity-75"><%= post.published_at.strftime('%d %B %Y') %></aside>
        <%= h2(post.title, "text-center mt-2 mb-4") %>
        <p class='prose lg:prose-xl dark:prose-dark'><%= post.content.to_plain_text.truncate(256) %></p>
        <p class='my-4 text-center'><%= link_to 'Read More', post, class: button_css('purple') %></p>
      </article>
    <% end %>
</div>

app/views/posts/new.html.erb
<div class="max-w-2xl mx-auto">
<%= headline('New Post') %>

<%= render 'form', post: @post %>

<%= link_to 'Cancel', posts_path %>
</div>

app/views/posts/show.html.erb
<article class="<%=t('css_article')%>">
<%= render 'components/actions', obj: @post %>
<aside class="text-center text-gray-500 opacity-75"><%= @post.published_at.strftime('%d %B %Y') %></aside>
<div class="text-center"><%= headline(@post.title) %></div>

<section class="mb-12 font-serif prose max-w-prose lg:prose-xl dark:prose-dark">
<%= @post.content %>
</section>

<%= render 'components/subscribe' %>
</article>