config/routes.rb
Rails.application.routes.draw do
  
  resources :subscriptions
  resources :confirmations
  resources :praises
  resources :books
  resources :series
  devise_for :users
  get 'landing/index'
  resources :posts

  resources :pages
  get '/:slug' => "pages#show"
  
  root to: 'landing#index'
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_series, only: %i[ show edit update destroy ]

  # GET /series or /series.json
  def index
    @series = Series.all
  end

  # GET /series/1 or /series/1.json
  def show
  end

  # GET /series/new
  def new
    @series = Series.new
  end

  # GET /series/1/edit
  def edit
  end

  # POST /series or /series.json
  def create
    @series = Series.new(series_params)

    respond_to do |format|
      if @series.save
        format.html { redirect_to @series, notice: "Series was successfully created." }
        format.json { render :show, status: :created, location: @series }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1 or /series/1.json
  def update
    respond_to do |format|
      if @series.update(series_params)
        format.html { redirect_to @series, notice: "Series was successfully updated." }
        format.json { render :show, status: :ok, location: @series }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1 or /series/1.json
  def destroy
    @series.destroy
    respond_to do |format|
      format.html { redirect_to series_index_url, notice: "Series was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Series.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def series_params
      params.require(:series).permit(:title, :content)
    end
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/series/_form.html.erb
<%= form_with(model: series) do |form| %>
  <% if series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
        <% series.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-input w-full rounded' %>
  </div>

  <div class="my-4">
    <%= h2('Synopsis') %>
    <%= form.rich_text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit "Submit", class: button_css('blue')%>
  </div>
<% end %>

app/views/series/edit.html.erb
<div class="<%=t('css_article')%>">

<%= headline("Editing: #{@series.title}") %>

<%= render 'form', series: @series %>
</div>

app/views/series/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Series</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @series.each do |series| %>
      <tr>
        <td><%= series.title %></td>
        <td><%= series.content %></td>
        <td><%= link_to 'Show', series %></td>
        <td><%= link_to 'Edit', edit_series_path(series) %></td>
        <td><%= link_to 'Destroy', series, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Series', new_series_path %>

app/views/series/new.html.erb
<div class="<%=t('css_article')%>">

<%= headline('New Series') %>

<%= render 'form', series: @series %>
</div>

app/views/series/show.html.erb
<div class="<%=t('css_article')%>">
  <%= render 'components/actions', obj: @series %>
  <%= headline(@series.title) %>
  <section class='<%= t('prose') %>'>
    <%= @series.content %>
  </section>
</div>